name: samaritan-person-detection
channels:
- defaults
dependencies:
- pillow=4.2.1
- scipy=0.19.0
- h5py=2.7.1
- pip:
  - tensorflow==1.3.0
  - keras==2.0.8
  - kafka-python==1.3.5
  - statsd=3.2.1
  - perfmetrics==2.0
