name: samaritan-person-detection
channels:
- defaults
dependencies:
- python=3.6
- pillow=4.2.1
- scipy=0.19.0
- h5py=2.7.1
- pip:
  - tensorflow-gpu==1.3.0
  - keras==2.0.8
  - kafka-python==1.3.5
  - statsd==3.2.1
