name: samaritan-person-detection
channels:
- defaults
dependencies:
- pillow=4.2.1
- scipy=0.19.0
- h5py=2.7.1
- pip:
  - https://anaconda.org/intel/tensorflow/1.3.0/download/tensorflow-1.3.0-cp36-cp36m-linux_x86_64.whl
  - keras==2.0.8
  - kafka-python==1.3.5
  - statsd==3.2.1
