name: yad2k
channels:
- defaults
- intel
dependencies:
- python=3.6
- pillow=4.2.*
- scipy=0.19.*
- h5py=2.7.*
- tensorflow-tensorboard=0.1.*
- protobuf=3.4.*
- scikit-learn
- pip:
  - /tmp/pip/tensorflow-1.3.1-cp36-cp36m-linux_x86_64.whl
  - kafka-python==1.3.5
  - opencv-python
  - statsd==3.2.1
